#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

docker run -w /lua --rm -it -v ${PWD}:/lua test-cli luacheck -q lib
docker run -w /lua --rm -it -v ${PWD}:/lua test-cli lj-releng lib/resty/*.lua lib/resty/**/*.lua lib/resty/**/**/*.lua
