name: CI

on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and start necessary containers
        run: docker-compose up -d

      - name: Spec
        run: |
          docker-compose exec -T proxy /scripts/spec
